FROM centos:7
LABEL description="MAPDL RC2 v211"

RUN yum install \
    openssl openssh-clients mesa-libGL mesa-libGLU motif libgfortran \
    -y && yum clean all && rm -rf /var/cache/yum

RUN mkdir -p /ansys_inc
COPY v211 /ansys_inc/v211
ENTRYPOINT ["/ansys_inc/v211/ansys/bin/mapdl", "-grpc"]
